atlas_org_id = "5fae6add6dbf6b0a4aeadfc1"
atlas_project_name = "My2ndProject"
environment = "dev"
cluster_instance_size_name = "M0"
cloud_provider = "AWS"
atlas_region = "AP-SOUTHEAST-1"
mongodb_version = "7.0"
ip_address = "116.14.185.167"
